# Generated by Django 4.1.3 on 2022-12-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='item')),
                ('price', models.IntegerField(max_length=3, verbose_name='price')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
