# Generated by Django 4.1.3 on 2023-01-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
    ]
