# Generated by Django 4.1.3 on 2023-01-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_clicked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='clicked',
            field=models.BooleanField(default=False, verbose_name='clicked'),
        ),
    ]
