# Generated by Django 4.1.3 on 2023-01-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, default='masih', max_length=30, verbose_name='Name'),
        ),
    ]
