# Generated by Django 4.1.3 on 2023-01-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='clicked',
        ),
    ]
