# Generated by Django 4.1.3 on 2022-12-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=40, verbose_name='items')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
