# Generated by Django 3.2.4 on 2022-12-31 23:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_carts_items_carts_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='cart_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
