# Generated by Django 4.1.3 on 2023-01-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_carts_cart_ids_remove_carts_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='quantity',
            field=models.IntegerField(db_index=True, default=0, verbose_name='quantity'),
        ),
    ]
