# Generated by Django 4.1.3 on 2023-01-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_carts_created_at_carts_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='name',
            field=models.CharField(default='anonymous', max_length=30, verbose_name='name'),
        ),
    ]
