# Generated by Django 4.1.3 on 2023-01-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_updated_at'),
        ('carts', '0007_carts_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='name',
        ),
        migrations.AlterField(
            model_name='carts',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
