# Generated by Django 4.1.3 on 2023-01-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_remove_carts_name_alter_carts_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='item',
        ),
    ]
