# Generated by Django 4.1.3 on 2023-01-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_item_name'),
        ('carts', '0009_remove_carts_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
