# Generated by Django 4.1.3 on 2023-01-06 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_item_name'),
        ('carts', '0011_alter_carts_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='items.item'),
        ),
    ]
