# Generated by Django 4.1.3 on 2022-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('likes', models.IntegerField(max_length=1)),
                ('review', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
