# Generated by Django 4.1.3 on 2022-12-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='likes',
            field=models.PositiveIntegerField(max_length=1),
        ),
    ]
