# Generated by Django 4.1.3 on 2022-12-27 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='likes',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
