# Generated by Django 4.1.3 on 2023-01-09 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_item_name'),
        ('reviews', '0003_alter_reviews_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_name_reviews', to='items.item'),
        ),
    ]
